services:
  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  labseq:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: labseq
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_REDIS_HOSTS=redis://redis:6379
    depends_on:
      - redis
